### ISSUE TITLE
Way to share context betwen Bot and Command::Base?

### ISSUE THREAD

**Issue by gargath** [slack-ruby/slack-ruby-bot#100]
When adding commands to a class derived from `SlackRubyBot::Bot`, it is easy to share common state between commands using instance variables.

How can I achieve the same thing when using commands implemented on `SlackRubyBot::Commands::Base`?

In my case, I would like to use one command to instruct the bot to update local state from an external REST endpoint and another to query this local state.

I guess I'm looking for something akin to Rack's `env`.

**Comment by dblock** [comment]
When you mean "local state", you mean global for the current instance of the bot? I would just create a separate class and use class variables from there, for example:

```ruby
class State
   attr_accessor :foobar

   def self.instance
      @instance ||= new
   end
end
```

.... and elsewhere

```
State.instance.foobar
```
