### ISSUE TITLE
possible to capture snippet?

### ISSUE THREAD

**Issue by tk8817** [slack-ruby/slack-ruby-bot#103]
Hi folks! 

Is it possible to capture / read snippets with slack-ruby-client or slack-ruby-bot? we love the framework but have found that sometimes the slack message limit gets in the way of taking input for a certain command (like opening a JIRA TT with a big description)

**Comment by dblock** [comment]
This is probably more of a slack API question. Do you mean in RealTime API when you see those `message` events you're not seeing snippets? Or the full text of a message?
