### ISSUE TITLE
Events API Support

### ISSUE THREAD

**Issue by Roach** [slack-ruby/slack-ruby-bot#104]
💡 This is not a bug report so much as it's intended to be a discussion about what the best solution would be in the context of this SDK.

At Slack, we've been putting together a few tutorials around using various SDKs to implement the Slack Events API into an app or bot. One of those tutorials was written using this library and a simple Sinatra app to provide endpoints for Events API calls *from* Slack. While that approach is more of a boilerplate for new developers or experienced developers to use as a starting point, we've also been discussing what it might look like to add this support to some of the SDKs themselves.

Adding Events API support has the potential to improve the development workflows and time it takes to build and troubleshoot Slack apps, but it comes with the cost of added dependencies and complexity in the SDK itself. In the Ruby ecosystem, for example, I think the most likely candidates would be Grape or Sinatra.

I'd love to hear your thoughts @dblock, as well as those of your community. 🤖

**Comment by dblock** [comment]
If I understand correctly you'd like slack-ruby-bot to support events delivered via HTTP GET/POST? Support things like slash commands? I think it's a great idea, developers want all-in-one solutions that are super easy to put together.

https://github.com/slack-ruby/slack-ruby-bot-server could be another place to do this, as it solves higher level problems. 

Generally you want to be able to decompose things in gems, so if I am writing a Rails app I should be able to take slack-ruby-bot, slack-rails-api (doesn't exist) and tie all these things together super easily.

**Comment by Roach** [comment]
Oops, I realize now that I posted this to the wrong repo. I meant to post it in ruby-slack-client.

I agree with the idea of an a la carte model to include only the items a developer would want, rather than a massive collection of dependencies a developer may not use. I need to do a bit of research regarding gems that invoke a webserver to see what the existing strategies are...

**Comment by zenmatt** [comment]
Wondering if there's been any progress on this? Would love to switch to the events API from rtm using this library.

**Comment by dblock** [comment]
not AFAIK

**Comment by zenmatt** [comment]
What would be the best way to tackle this? The Events API provides an easier foundation to build scalable bots and it looks like Slack is putting it on equal ground with the Realtime API. I'm going to rewrite our bot to use it and would like to contribute back to this library if possible.

**Comment by dblock** [comment]
I would start in [slack-api-ref](https://github.com/slack-ruby/slack-api-ref) and work up the stack from there.

**Comment by dblock** [comment]
@alexagranov

**Comment by alexagranov** [comment]
@dblock Got it.

For my testing so far, all I've had to do was add an endpoint to my Sinatra server, `/events`, and then registered that as the Request URL on the Slack "Event Subscriptions" page for the app in question.

I then just break out specific event handling logic via case-statement - I'm only listening for things like `team_join`, `tokens_revoked`, and (god forbid) `app_uninstalled` so far, but I don't see it being an issue to handle something like `app_mention` and reply back to User via Web API.  Action callbacks (buttons, dialog submissions) and slash commands already have their own respective endpoints.

As far as I can see, there is no way to automate event subscription via API (https://api.slack.com/events-api#subscriptions) - everything has to be done manually on the Slack app developer page - so I'm left wondering:  

1. Is there really anything left for us to do in [slack-api-ref](https://github.com/slack-ruby/slack-api-ref)?  Or [slack-ruby-client](https://github.com/slack-ruby/slack-ruby-client) for that matter?

2. Do we just need to parse the `text` of an `app_mention` and invoke the [message hook call method](https://github.com/slack-ruby/slack-ruby-bot/blob/master/lib/slack-ruby-bot/hooks/message.rb#L4) which should route to the appropriate registered command for us?

**Comment by alexagranov** [comment]
Thinking about this some more...I'm wondering if there isn't overlap here with the desire for slash command support (#68):

In our bot, I ended up abstracting how slash commands (via Sinatra endpoint) and slack-ruby-bot `command` handlers (via RTM) respond with the use of ActiveJob - as many of the tasks we offer will take longer to execute than the maximum time Slack allows for slash commands to return a response.

Should we separate how command handlers are registered ("routing") - which the current dsl handles nicely - from some kind of "executor" interface that allows developers to implement either sync or async responses?

**Comment by dblock** [comment]
@alexagranov - I don't have good answers to these specific questions, but I'd like to be able to take a bot that I have written (eg. https://github.com/slack-ruby/slack-shellbot) and turn it into a bot that is not RTM based, but event based with some configuration.

**Comment by alexagranov** [comment]
@dblock Gotchya.  Let me think about this some more, but I may start proposing a direction in a PR soon.

**Comment by alexagranov** [comment]
@dblock I've fully moved over to Events API and am happy to report my bots don't need to be invited into people's sensitive channels - as well as no disconnect issues.

Looked around here some more and I do think we could leverage the MVC pattern, as exemplified by the Inventory example:
- Controllers can continue to define instance methods that are offloaded to `command` blocks
- Controllers could offer another mechanism for delegating Event API events to instance methods for handling
- Views can offload response handling to whichever `client` implementation - RTM or Web - has been injected
- It would still be up to upstream (slack-ruby-bot-server) to serve endpoints via Sinatra/Rails and instantiate Controllers as necessary

I think the first bit to bite off is to abstract the SlackRubyBot::Client away from being a pure Slack::RealTime::Client and allow for "bot" clients to also be a Slack::Web::Client when injected into Controllers.  This way Web clients can offer their own implementation of `say` which everything is using right now.

How does that sound?

**Comment by dblock** [comment]
This seems like a reasonable step to make things easy, give it a shot, make some PRs :)

**Comment by dblock** [comment]
I've started https://github.com/slack-ruby/slack-ruby-bot-server-slack that makes it easier to handle events, slash commands and interactive buttons with slack-ruby-bot-server, if anyone wants to try it.

**Comment by dblock** [comment]
Released https://github.com/slack-ruby/slack-ruby-bot-server-events that has complete events, slash commands and actions support.
