### ISSUE TITLE
Catchall for private IM message directly to the bot

### ISSUE THREAD

**Issue by cromulus** [slack-ruby/slack-ruby-bot#109]
Hi!

I have a bot that is supposed to take all text sent directly to it and post it to a url and return the response. Think like `irb` but via private message directly with the bot.

The bot also has generic commands that it responds to in public channels, like `ping` etc.

How would I specify a catchall for the private messages so that my slack users do not have to preface each line of their irb session with a command?

**Comment by dblock** [comment]
By default slack-ruby-bot answers DMs directly without being mentioned. Have you tried it?

**Comment by cromulus** [comment]
Yes, I know. 

However, I do not want to specify a 'command' for the DM, instead for the bot to accept any message and execute the text. 

For example, in a DM to @bot, I would message "ps auxf" and the bot would respond with all running processes. Or I could DM 'uptime' or any other bash script and it would execute it. 

Right now, the bot responds with the default "command not found". I want to override the "command not found" response. 

Make sense? 

Sent on the move.

**Comment by dblock** [comment]
One way to do it is to do a custom match, like slack-google-bot in https://github.com/dblock/slack-google-bot/blob/master/slack-google-bot/commands/google.rb, or the slack-api-explorer in https://github.com/dblock/slack-api-explorer/blob/master/slack-api-explorer/commands/slack.rb.

You can also "see" and then handle all messages in an `on :message` hook.

**Comment by cromulus** [comment]
It works!
`match(/^(?<bot>\w*)\s(?<expression>.*)$/)` is an effective catchall.

Thanks!
