### ISSUE TITLE
Bot client can't DM users

### ISSUE THREAD

**Issue by thesmart** [slack-ruby/slack-ruby-bot#112]
I can't figure out how to get `client.say` to send private DMs to the `data.user` invoking the command.  It `client.say` returns true, even though nothing is sent.

This works differently than the Web API where a user's id can be used to send DM to without having to open the IM first.

**Comment by dblock** [comment]
The slack dock doesn't say anything crazy.

![screen shot 2017-02-10 at 11 19 53 am](https://cloud.githubusercontent.com/assets/542335/22834363/e06eb492-ef82-11e6-939b-320136789de2.png)

**Comment by thesmart** [comment]
Ah, need to open the IM first. Thanks!

**Comment by dblock** [comment]
Would you post working code here for the next person? Maybe even PR it into README?

**Comment by thesmart** [comment]
Not sure this is the canonical way of doing this, but I'd happily update the README if you can tell me if this is the canonical way that makes sense for the README:

I created a helper method in my `SlackRubyBot::Bot` class
```ruby
      # Get the bot's Slack API client
      def slack_client
        @slack_client ||= ::Slack::Web::Client.new(token: ENV['SLACK_API_TOKEN'])
      end

      # returns the channel id of an open IM channel
      def self.slack_im_open!(user_slack_id)
        @im_opens ||= {}
        return @im_opens[user_slack_id] if @im_opens[user_slack_id]

        begin
          im = slack_client.im_open(user: user_slack_id)
          im_channel_id = im && im['channel'] && im['channel']['id']
          return @im_opens[user_slack_id] = im_channel_id
        rescue => err
          STDERR.puts err.to_s
          STDERR.puts "Error opening IM channel: #{user_slack_id}"
          return nil
        end
      end
```

**Comment by dblock** [comment]
Interesting. Why wouldn't you just go the web client way to DM the user in this case, which always works?

I'm going to close this since we've figured out what's going on. I think this is too involved for the README.
