### ISSUE TITLE
Problem with starting of the Bot Server for a big number of teams (200+)

### ISSUE THREAD

**Issue by dmitriy1703** [slack-ruby/slack-ruby-bot#122]
The issue is in the next. When we run the Puma Server - connection with the Bot is set up for a while - Bot becomes online BUT at once after that goes offlne. We use the next approach - we keep team tokens in the database. When we start the Puma Server then we use the same approach for setting up server connection as is written in the readme of the Bot. 
```ruby
MUTEX = Mutex.new
servers = {}
tokens.each_with_index do |token, id|
  MUTEX.synchronize do
    instance = SlackRubyBot::Server.new(token: token)
    instance.start_async
    servers[id] = instance
  end
end
```
Also, please, note that small number of teams are still online.
We use AWS EC2 instances:
t2.micro - allows successfully start the Bot in approximately 10 teams and in this case there are no problems with Bot going offline
t2.medium - allows successfully start the Bot in approximately 150 teams without any fails.
When instances of Class SlackRubyBot::Server - the ruby process sharply increase the load on CPU that's why t2.medium allows to successfullly start connections for bigger number of teams.
What could be the reasons of Bot going offline?
What other approaches could be used for setting up connection?

**Comment by dblock** [comment]
Look at memory usage of the process, is it getting to a place where it eats up all the ram? 

I've been quite successful reducing the memory usage with using a different store, see https://github.com/slack-ruby/slack-ruby-client#slackrealtimestoresstore. If you're not using any local store data you can get rid of it, particularly useful for large teams.

**Comment by kirillweb** [comment]
with ram all looks like ok, but ruby process load cpu around 50%

**Comment by dblock** [comment]
Starting a connection for 150 teams involves downloading 150 multi-megabyte JSONs and parsing them. I think you should try with a `nil` store next as well.

**Comment by dblock** [comment]
Slack added `rtm.connect`, which no longer sends any more information than needed to the client on start unlike `rtm.start`. I've implemented support for it in slack-ruby-client in https://github.com/slack-ruby/slack-ruby-client/pull/145, you should try slack-ruby-client#HEAD, it has dramatically improved the memory footprint and connection speed of my [game bot](https://www.playplay.io/) that currently has 385 active teams.

**Comment by kirillshevch** [comment]
Thanks for update! @dblock
Do you use any tools to tracking state(online/offline) of bot?

**Comment by dblock** [comment]
@kirillshevch https://github.com/slack-ruby/slack-ruby-bot-server for example exposes an endpoint that calls `ping`, and I use Uptime Robot to check that for my bots. And ping is implemented as a web API call for presence - https://github.com/slack-ruby/slack-ruby-bot-server/blob/master/lib/slack-ruby-bot-server/models/team/methods.rb#L33.

**Comment by kirillshevch** [comment]
We just switched to celluloid and now we have no problems. With EM, connections was broken аfter the connection was established more then 15 teams on EC2 medium instance ([restart](https://github.com/slack-ruby/slack-ruby-bot/blob/26240b3f5f120bd3f9e3b9a63a9a1b2666ff8324/lib/slack-ruby-bot/server.rb#L51) just did not work in this case). 
```ruby
Slack::RealTime.configure do |config|
  config.concurrency = Slack::RealTime::Concurrency::Celluloid
end
```

**Comment by kirillshevch** [comment]
Now about 50 installations and everything is OK.

**Comment by dblock** [comment]
Closing this.
