### ISSUE TITLE
Issue starting bot with puma daemonized

### ISSUE THREAD

**Issue by jonsgreen** [slack-ruby/slack-ruby-bot#129]
This is maybe not really an issue but I am not sure if there is a better place to ask this question. I am trying to start a bot (actually potentially several) from a Rails application in config.ru. It seems to work fine in development but when I use my production puma configuration something fails when I have daemonize set to true. I am curious if you have any idea why that might be the case.

**Comment by dblock** [comment]
Can you please provide some more information than "something fails"? Thanks.

**Comment by jonsgreen** [comment]
Sorry, I was not necessarily sure whether this would even be worthy of your attention and I really appreciate your support. Here is a gist of the relevant code: https://gist.github.com/jonsgreen/5806f6c56a68fc71d9ed756f62dba131. 

When I run with the daemonize I am able to just catch this trace in the puma.stderr.log:
```
/Users/jonathangreenberg/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/uuid.rb:21:in `synchronize': can't be called from trap context (ThreadError)
        from /Users/jonathangreenberg/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/uuid.rb:21:in `generate'
        from /Users/jonathangreenberg/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:92:in `uuid'
        from /Users/jonathangreenberg/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/mailbox.rb:17:in `initialize'
        from /Users/jonathangreenberg/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:87:in `new'
        from /Users/jonathangreenberg/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid.rb:87:in `mailbox'
        from /Users/jonathangreenberg/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:20:in `method_missing'
        from /Users/jonathangreenberg/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/slack-ruby-client-0.8.0/lib/slack/real_time/client.rb:68:in `started?'
        from /Users/jonathangreenberg/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/slack-ruby-client-0.8.0/lib/slack/real_time/client.rb:63:in `stop!'
        from /Users/jonathangreenberg/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/slack-ruby-bot-0.10.1/lib/slack-ruby-bot/server.rb:48:in `stop!'
        from /Users/jonathangreenberg/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/slack-ruby-bot-0.10.1/lib/slack-ruby-bot/server.rb:91:in `block (2 levels) in handle_signals'
        from /Users/jonathangreenberg/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:448:in `select'
        from /Users/jonathangreenberg/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/cluster.rb:448:in `run'
        from /Users/jonathangreenberg/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/puma/launcher.rb:172:in `run'
        from /Users/jonathangreenberg/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/puma-3.6.0/lib/rack/handler/puma.rb:51:in `run'
        from /Users/jonathangreenberg/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/rack-2.0.1/lib/rack/server.rb:296:in `start'
        from /Users/jonathangreenberg/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/server.rb:79:in `start'
        from /Users/jonathangreenberg/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:90:in `block in server'
        from /Users/jonathangreenberg/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
        from /Users/jonathangreenberg/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
        from /Users/jonathangreenberg/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /Users/jonathangreenberg/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
```

As you can see I am probably not doing something all that conventional and perhaps with your deeper understanding of the code would be able to suggest a better approach to supporting starting and running multiple bots. I know you have the slack_ruby_bot_server gem somewhat for that purpose but it seemed to be more than what I needed and I was unsure of how to bend that one for my current needs. I actually really only need to be running one bot at this time so the critical piece is figuring out the best way to get one started with puma daemonized on production. Any suggestions will be greatly appreciated and thanks so much for all the work you do supporting and promoting slack bots in the ruby community and beyond!

**Comment by dblock** [comment]
The error I think explains what's going on, but might not explain what to do to fix it. The code probably looks like this:

```
trap("INT") { ... start the bot here ... }
```

Celluloid (or EventMachine) don't seem to like it. There seem to be a lot of [google hits on this](https://www.google.com/search?q=synchronize%27%3A+can%27t+be+called+from+trap+context&oq=synchronize%27%3A+can%27t+be+called+from+trap+context&aqs=chrome..69i57.110j0j4&sourceid=chrome&ie=UTF-8#q=synchronize':+can't+be+called+from+trap+context+celluloid) and none are proposing any solutions, so you need to take the bot initialization out of this. 

Check out https://github.com/slack-ruby/slack-bot-on-rails and how it starts the bot [from a thread](https://github.com/slack-ruby/slack-bot-on-rails/blob/master/config.ru#L6). That should work.

**Comment by jonsgreen** [comment]
If you look at the gist I believe I am starting my bot from a thread no? I got that approach from your code which is why I thought perhaps you might have a suggestion for how to do this differently. I will look into some of the similar errors people are having.

**Comment by jonsgreen** [comment]
Just for posterity here...
It seems like just adding a 1 second sleep in between starting the bots and the rails app seems to have solved the problem. Go figure.

**Comment by jonsgreen** [comment]
In case someone else stumbles upon this I was not able to figure out how to keep my bot clients from closing using puma with daemonizing. Something about calling Process.daemon(true) forced my bots to exit. I ended up moving starting them out of config.ru and instead used the daemons gem to manage starting and stopping my bot(s). I am sure there are many others ways to skin this cat.
