### ISSUE TITLE
Project open to accepting a patch with `before`/`after` hooks on commands?

### ISSUE THREAD

**Issue by chuckremes** [slack-ruby/slack-ruby-bot#132]
I've written a patch that allows a programmer to add global and verb-specific `before` and `after` blocks to commands. A global `before` / `after` would run before/after every command. A verb-specific hook would only run before/after that specific command. Here's an example:

```ruby
# In SlackRubyBot::Commands::Base or a subclass...
class Foo < SlackRubyBot::Commands::Base

  # Global before hook called before any command
  before do |client, data, match|
    client.say(channel: data.channel, text: "1st Global BEFORE block, runs first.")
  end

   before 'some_command' do |client, data, match|
     client.say(channel: data.channel, text: "Verb-specific BEFORE block.")
   end
   
   after do |client, data, match|
     client.say(channel: data.channel, text: "Global AFTER block, runs last.")
   end

  command 'some_command' do |client, data, match|
    # ...
   end
end
```

I was going to release this as a simple gem that monkey-patched this project but it occurred to me that you might want it. Let me know if you would accept a pull request with this type of functionality.

I do have specs for this too.

**Comment by dblock** [comment]
Yes, please contribute!

**Comment by chuckremes** [comment]
Opened a PR for this.
