### ISSUE TITLE
GIFs should be team-wise enabled or disabled

### ISSUE THREAD

**Issue by nileshtrivedi** [slack-ruby/slack-ruby-bot#148]
GIFs are fun but can get annoying at times. The bot should call a hook method, passing data such as `team_id` and send GIFs only if this method - which the developer would implement - returns true. Then each team could maintain its own GIF preference (as a boolean column in `teams` table) and toggle it using a custom command.

Only the callback method needs to be provided by the library, rest of the implementation can be left to the developer using this library.

**Comment by chuckremes** [comment]
I like this idea. It sounds like something I don't need yet but will want sometime soon. Ideally it wouldn't be tied to `team_id` but could match against some arbitrary information passed to the hook/callback.

Do you have code for this proposal?

**Comment by nileshtrivedi** [comment]
Unfortunately, no. I am still trying to wrap my head around all the layers of abstraction. Needed this for my bot so posted as a feature request.

**Comment by dblock** [comment]
Support for GIFs was removed in #263.
