### ISSUE TITLE
Cleanest way to customize help command?

### ISSUE THREAD

**Issue by mcritchlow** [slack-ruby/slack-ruby-bot#151]
The default help command and pattern works great for describing an implemented bot and new commands. 

I want to [remove this line](https://github.com/slack-ruby/slack-ruby-bot/blob/master/lib/slack-ruby-bot/commands/help.rb#L35) pointing people to this repo, but otherwise use the pattern as-is. I'm wondering if there's any guidance on the least invasive way to do this? Thanks in advance.

**Comment by dblock** [comment]
For this I would just monkey-patch it. See #59 for a cleaner version of what we want, maybe you can contribute?
