### ISSUE TITLE
How do I override the default command?

### ISSUE THREAD

**Issue by jilustrisimo** [slack-ruby/slack-ruby-bot#152]
I understand how to override the other built-in commands such as `about` and `hi` but I'm lost as to how to override the response when someone just types in the bots name.

**Comment by kstole** [comment]
I don't know if there's a more idiomatic way to do it but you can just use the match command that SlackRubyBot uses to match the bot's name.
```ruby
# Default/about command provide information about the bot
class Default < SlackRubyBot::Commands::Base
  command 'about'
  match(/^(?<bot>[[:alnum:][:punct:]@<>]*)$/u)

  def self.call(client, data, _match)
    client.say(channel: data.channel, text: ABOUT)
  end
end
```

**Comment by jilustrisimo** [comment]
works, thanks
