### ISSUE TITLE
Retrieve channel id for bot.say()

### ISSUE THREAD

**Issue by jillguyonnet** [slack-ruby/slack-ruby-bot#156]
Hey, potentially naive question here.

All command examples I have found use `client.say(text: 'foo', channel: data.user)` to send a message to the same channel the command was issued from. I'm trying to send messages either to specified channels or directly to some specified user. It seems that `say` only accepts channel ids, so I was trying to retrieve them via `client.channels` and `client.ims` respectively. However, these come back as empty. The channels don't seem to have been registered in the store.

Any pointers? Thanks and apologies if I've missed anything obvious.

**Comment by dblock** [comment]
There're a few ways to do this.

Slack will resolve '#channel` and `@user` for you, so `say` is happy to pass that along. I think that's the easiest, so I would just try that.

The store will keep things up-to-date if you use one, I believe we use the `nil` store that stores nothing or close to nothing. See https://github.com/slack-ruby/slack-ruby-client#slackrealtimestoresstore for more info.

You can enumerate channels with the web API, so `channel_info` and such. You can even open DMs to multiple people like [here](https://github.com/dblock/slack-sup/blob/master/slack-sup/models/sup.rb#L120)

I'll close this for now, add a note wrt what you chose and what worked.

**Comment by jillguyonnet** [comment]
Thanks dblock, the `nil` store explains what I got.

Neither `#channel` nor `@user` work with `say`. I thought `say` uses the RTM api, which expects a channel id, so I wasn't expecting it to work?

I ended up using a solution along the lines of what you did for sup bot, thanks for pointing me to that example.

**Comment by dblock** [comment]
Ah yes, real time API is different, you're right. If you do this a lot maybe change the store, but i think a web request works just as well.
