### ISSUE TITLE
Add RSpec regex expectations

### ISSUE THREAD

**Issue by dblock** [slack-ruby/slack-ruby-bot#158]
On the tail of https://github.com/slack-ruby/slack-ruby-bot/pull/157, allow regular expressions for message expectations.

**Comment by gcraig99** [comment]
This is working in #157. I didn't have to do anything special, it just worked based on the underlying expectations. I added tests for the expectations that include testing regex expectations.

**Comment by dblock** [comment]
Closing via #157.
