### ISSUE TITLE
Get image with command

### ISSUE THREAD

**Issue by craigsheen** [slack-ruby/slack-ruby-bot#161]
Hi,

Love this! However is it possible to get an image with a command?

**Comment by dblock** [comment]
I don't think I quite understand the question :) Slack will unfurl images if you just send the URL in the response.

**Comment by kstole** [comment]
You can also include images in attachments with the Web API using the `image_url` property.
https://api.slack.com/docs/message-attachments#image_url

**Comment by craigsheen** [comment]
Sorry I wasn’t very clear. I have a bot which you can say things to and then it will store what you tell it. I.e.

`faqbot store q: what is my favourite colour? a: blue`

What I would like is to be to able to upload an image with that command and it be sent to the server with the command text. So if I type the above then paste in an image of a blue square for example it would all be sent together.

When I do this currently slack will show the image and then the “command” will become a title or comment on the image and the bot won’t then pick up the command. I was wondering if there was a work a round or a way to do this.

I found that if I upload an image to slack and then type the command and copy the image url and paste it in this kind of works. Slack bot actually receives this with surrounding <>. I could just remove these when passing it back down to render in slack though and it does intact unfurl. I don’t think this would work if I upload an image in a private channel though and then tried to unfurl it in a public channel.

Hopefully that makes more sense.

Thanks,
Craig

Sent from my iPhone

On 5 Oct 2017, at 2:12 am, Kyler Stole <notifications@github.com<mailto:notifications@github.com>> wrote:


You can also include images in attachments with the Web API using the image_url property.
https://api.slack.com/docs/message-attachments#image_url

**Comment by dblock** [comment]
The bot sees all messages on the channel including images being uploaded, no? You need a [hook](https://github.com/slack-ruby/slack-ruby-bot#hooks) for [file_created](https://api.slack.com/events/file_created) I believe.

**Comment by craigsheen** [comment]
Ah, perfect! I can indeed use that. Thanks!
