### ISSUE TITLE
Display name support?

### ISSUE THREAD

**Issue by CoralineAda** [slack-ruby/slack-ruby-bot#162]
I'm currently using Slackbotsy for my bot, which gives me the `user_id` and `user_name` for a message posted to a channel. In the slack-ruby-bot source I see `data.user` but it's not clear to me what that contains. Can I get something like `data.user.display_name`? 

Forgive me for being lazy and asking before I rip out the existing bot gem and replace it.

**Comment by dblock** [comment]
Did you answer your own question @CoralineAda? Care to tell us what you did for the next person?

**Comment by CoralineAda** [comment]
I decided to just add an API call outside of the bot framework to get user info. I only needed it for when a new user interacted with the bot for the first time, so that seemed lower-friction than anything else. The only gotcha I encountered is that the display name isn’t ALWAYS populated, so I need to fall back to user name in those cases. What a mess.

**Comment by jonmchan** [comment]
FYI for others, to get user information, we can pull it from the client.store.users hash:

`client.store.users[data.user]['name']`

may be useful to add this to the docs.

**Comment by ATParente** [comment]
Please consider adding this info as suggested. Just the line John posted was a huge help to me in working with the client object vs the default documentation. Thank You.
