### ISSUE TITLE
Bot replies even if not mentioned with regular expressions match

### ISSUE THREAD

**Issue by Startouf** [slack-ruby/slack-ruby-bot#169]
I don't know if this was an expected feature, but I just deployed a bot in production, and had to disable it since regex were matching even when the bot wasn't mention and this had unintended side effect

For example

```ruby
match /(hello|coucou|ça va|hi/hola)/
```

Would actually match a lot of sentences like `hired`, etc. even if the bot name isn't mentioned

**Comment by kstole** [comment]
The `match` method will match the provided regex as-is. Use the `command` method instead to prepend a bot matcher to the regex.

**Comment by dblock** [comment]
@kstole is correct, closing
