### ISSUE TITLE
Can't write spec against web_client.chat_postMessage messages

### ISSUE THREAD

**Issue by jamesez** [slack-ruby/slack-ruby-bot#192]
I've Googled around and I'm not sure how to write a spec that matches against the bot replying via  client.web_client.chat_postMessage.

I did find a blog post (https://subvisual.co/blog/posts/102-the-pain-of-testing-with-3rd-party-integrations/) that described using an injecting an adapter class to collect them, but doing that I get a stack limit calling FakeSlackClient.new.

Does anyone have a concrete example of a test against chat_postMessage?

**Comment by dblock** [comment]
I would just use `expect` and get hold of the slack client object, like [here](https://github.com/dblock/slack-strava/blob/c527735efe10f908c2989ee449d8b691d115aa45/spec/models/club_activity_spec.rb#L9). And when not possible, expect any instance of a client to receive the method, [eg](https://github.com/dblock/slack-strava/blob/d70e32939b76934943fc0fc7260454874b5b416c/spec/api/endpoints/slack_endpoint_spec.rb#L29).

```ruby
expect_any_instance_of(Slack::Web::Client).to receive(:chat_postMessage).with(...)
```
