### ISSUE TITLE
Get bot to initiate messaging

### ISSUE THREAD

**Issue by dansteele** [slack-ruby/slack-ruby-bot#194]
Heyo,

I've had a bit of a fiddle - I'm trying to get the bot to initiate the messaging, IE not replying to an incoming command. I can persist the channel fine, but I'm not quite sure what to do with the Client object.

Any suggestions or examples welcome!
Thanks

**Comment by dblock** [comment]
You can use the web api to do this, for [example](https://github.com/dblock/slack-strava/blob/c527735efe10f908c2989ee449d8b691d115aa45/slack-strava/models/club_activity.rb#L17). So `client.chat_postMessage ...`.

**Comment by dblock** [comment]
I'll close this, but feel free to ask more questions.
