### ISSUE TITLE
Sending direct messages

### ISSUE THREAD

**Issue by asalom** [slack-ruby/slack-ruby-bot#196]
Hi guys, I've a question. I can't seem to find a way to send a direct message to a user in the following case:

The bot is invited to a channel.
A user posts a message in that same channel saying hello.
I want the bot to send a direct message saying hello back to that user.

Is this possible?
Thank you

**Comment by dblock** [comment]
Check out https://github.com/dblock/slack-strava, it DMs the user [here](https://github.com/dblock/slack-strava/blob/d70e32939b76934943fc0fc7260454874b5b416c/slack-strava/models/user.rb#L113) via 

```ruby
im = team.slack_client.im_open(user: user_id)
team.slack_client.chat_postMessage(message.merge(channel: im['channel']['id'], as_user: true))
```

**Comment by asalom** [comment]
Thank you!
