### ISSUE TITLE
How to get custom field in user's profile

### ISSUE THREAD

**Issue by hlindberg** [slack-ruby/slack-ruby-bot#201]
I want to read a custom field in the profile of the user giving a command to my bot. How can I get that? It is not included in the user info already available. I could not figure out how to make the web_client.user_profile_get work - it ends with "not allowed", or when I experimented also error "not the correct kind of token". Then I got stuck. Answer or pointers much appreciated.

**Comment by dblock** [comment]
Your app needs the `users.profile:read` scope when it gets installed to enable this API to return data. This is something you request during "installation" of the bot. How do you implement "add to slack"?

**Comment by hlindberg** [comment]
Uhm, I don't really - using the defaults - giving the access token for the bot as an ENV variable, it connects.
My class is just this:
```
class Bot < SlackRubyBot::Bot
```
with some commands, scans and operators.

I figured out that `client.users[data.user].profile.fields[GITHUB_CUSTOM_FIELD].value` gives me the value of the custom field (I gleaned what the field id is and for now set it as a constant), but I would like to look it up - and I think that `user_profile_get` supplies the labels for the fields as an option.

If I should have requested this when I added the bot to slack then I don't know what to do now. It is not registered as an app. Maybe I was to fast when registering the bot and did not notice that permissions could be tuned. I tried regenerating the token thinking that may ask me, but it just gave me a new token.

**Comment by dblock** [comment]
I am not sure where this is. What's the exact process that you get this token from? Somewhere the scope of your app can be adjusted.

**Comment by hlindberg** [comment]
It is not an app, it is just a bot.

**Comment by dblock** [comment]
@hlindberg I read the docs. According to https://api.slack.com/docs/token-types _Bot user tokens have a broad set of permissions that cannot be modified_. What you need is an access token that has been requested with the right scope. 

I have an example that does this, [sup-bot](https://github.com/dblock/slack-sup/), which uses user profile fields [here](https://github.com/dblock/slack-sup/blob/cafea74bbf77af4882fbf2887db5d17b3b046f24/slack-sup/models/user.rb#L68). This access token is obtained via [oauth workflow](https://github.com/dblock/slack-sup/blob/cafea74bbf77af4882fbf2887db5d17b3b046f24/slack-sup/api/endpoints/teams_endpoint.rb#L51) from a web page which asks Slack to give the bot the `users.profile:get` permission [here](https://github.com/dblock/slack-sup/blob/cafea74bbf77af4882fbf2887db5d17b3b046f24/public/index.html.erb#L65).

I don't know how to create one of these for a custom bot integration that gives you a token once. I think you should ask Slack help. Let us know what you find.

**Comment by dblock** [comment]
Since this is obviously a token permissions problem I'll close this. Post here what you find though please!
