### ISSUE TITLE
Bot is unable to send messages.

### ISSUE THREAD

**Issue by madelaney** [slack-ruby/slack-ruby-bot#204]
When trying out the [minimal example](https://github.com/slack-ruby/slack-ruby-bot/tree/master/examples/minimal) I'm not able to get the bot to reply to a `ping` command.

After changing the logging level to `DEBUG`, I saw the following lines in the console:
```
D, [2018-11-19T08:56:04.073194 #74680] DEBUG -- SlackRubyBot::Client#run_loop: WebSocket::Driver::MessageEvent, {"type":"message","user":"U9GDA823B","text":"<@U9GSN01JP> ping","client_msg_id":"6beb726a-307a-45dd-a734-6986fffa8bdc","team":"T9H3NRVT7","channel":"C9H04HTL2","event_ts":"1542635764.004400","ts":"1542635764.004400"}
D, [2018-11-19T08:56:04.073456 #74680] DEBUG -- SlackRubyBot::Client#dispatch: channel=C9H04HTL2, client_msg_id=6beb726a-307a-45dd-a734-6986fffa8bdc, event_ts=1542635764.004400, team=T9H3NRVT7, text=<@U9GSN01JP> ping, ts=1542635764.004400, type=message, user=U9GDA823B
D, [2018-11-19T08:56:04.074284 #74680] DEBUG -- SlackRubyBot::Client#send_json: {:type=>"message", :id=>1, :text=>"pong", :channel=>"C9H04HTL2"}
D, [2018-11-19T08:56:04.077222 #74680] DEBUG -- Slack::RealTime::Concurrency::Celluloid::Socket#send_data: {"type":"message","id":1,"text":"pong","channel":"C9H04HTL2"}
D, [2018-11-19T08:56:04.077346 #74680] DEBUG -- Slack::RealTime::Concurrency::Celluloid::Socket#write: ??T???/???$???v̷?'???v??0???x???,???vѽ?3???7ɳ?:ľ?n????????)
.... 
D, [2018-11-19T08:56:10.098426 #74680] DEBUG -- Slack::RealTime::Concurrency::Celluloid::Socket#handle_read: ?b{"ok":false,"reply_to":1,"error":{"msg":"cannot process message","code":4,"source":"gs-iad-4g28"}}
D, [2018-11-19T08:56:10.098593 #74680] DEBUG -- SlackRubyBot::Client#run_loop: WebSocket::Driver::MessageEvent, {"ok":false,"reply_to":1,"error":{"msg":"cannot process message","code":4,"source":"gs-iad-4g28"}}
```

My current environment is as follows:
* Ruby 2.3.7 (on Mac OS X).
* Slack ruby bot (0.11.1).

**Comment by dblock** [comment]
I don't know what "cannot process message" and "code 4" could mean. Are you able to send/receive other messages?

**Comment by madelaney** [comment]
The bot is able to receive message, and subscribe to events (in general) but not send anything.

**Comment by dblock** [comment]
I'm going to close this, I am 99% sure this is a local problem and not something wrong in the library.

**Comment by ali-avvo** [comment]
I am getting the same problem.

**Comment by ali-avvo** [comment]
I was using ruby 2.3.3. I upgraded to ruby 2.7.1 and the same problem happen still.
@madelaney  did you find a solution?

**Comment by ali-avvo** [comment]
As a data point, I am successfully able to send message with slack-ruby-client in the same application with the same API token.

**Comment by dblock** [comment]
Either way I think you should try switching to async-websocket and see if the problem persists, we're deprecating the unmaintained Celluloid.

**Comment by ali-avvo** [comment]
@dblock I am already using `async-websocket` there is no reference of celluloid in my Gemfile or Gemfile.lock.
