### ISSUE TITLE
How to test when bot triggers typing event?

### ISSUE THREAD

**Issue by cabello** [slack-ruby/slack-ruby-bot#210]
Hi 👋 

I have a bot that takes a while to respond so I add a `typing` call to let the user on the other side know the bot is working on it. I am running into errors when writing specs for this command.

Bare bones example:

```ruby
module FooBot
  module Commands
    class Hello < SlackRubyBot::Commands::Base
      match(/hello/i) do |client, data, match|
        client.typing(channel: data.channel)
        sleep(3)
        client.say(channel: data.channel, text: 'Oh! Hi!!')
      end
    end
  end   
end
```

If I test this command using helpers like `respond_with_slack_message` then I get the following failure:

```
Slack::RealTime::Client::ClientNotStartedError:
  Slack::RealTime::Client::ClientNotStartedError
```

Can you provide some light on how to test this behaviour?

Thanks ❤️

**Comment by dblock** [comment]
This is a little tedious. You have to get a level lower.

```ruby
require 'spec_helper'

describe FooBot::Commands::Hello do
  let(:app) { Server.new }
  let(:client) { app.send(:client) }
  let(:message_hook) { SlackRubyBot::Hooks::Message.new }
  it 'receives typing' do
      expect(client).to receive(:typing)
      message_hook.call(client, Hashie::Mash.new(text: "#{SlackRubyBot.config.user} hello", channel: 'channel'))
    end
end
```

I think we should implement a matcher like `start_typing`, will label it as a feature request. Want to give it a shot @cabello?
