### ISSUE TITLE
Auth suddenly stopped working

### ISSUE THREAD

**Issue by snex** [slack-ruby/slack-ruby-bot#215]
Wrote a bot using this library 4 days ago, it worked fine. Today, it just suddenly stopped working and I get "invalid_auth" when running it. Went to the Slack admin and apparently they are deprecating the auth token? I was able to create a "legacy" token that allowed the bot to connect, but after doing this, the bot does not respond to commands or operators.

Seems like Slack might be moving in the direction of forcing OAuth.

**Comment by dblock** [comment]
So the bot connects? Is it visibly online in Slack? It's possible that the legacy token isn't a bot token?

**Comment by snex** [comment]
Bot connects and is visibly online. The log output even scrolls by as I type in things, but the bot does not respond at all or even recognize anything as a command/operator.

**Comment by dblock** [comment]
Did you upgrade slack-ruby-bot and some behavior has changed? Has the bot loaded your commands? You should debug what happens in [this code](https://github.com/slack-ruby/slack-ruby-bot/blob/master/lib/slack-ruby-bot/hooks/message.rb#L6) and walk the code to see why your command is not invoked.

**Comment by snex** [comment]
I have not upgraded at all, I started fresh on the latest version. Like I said, it worked fine a few days ago. Putting debug statements in that code yields no output at all.

**Comment by dblock** [comment]
Put the project up on Github and I can try to help.

**Comment by snex** [comment]
https://github.com/snex/pokerstove_slack_bot

**Comment by dblock** [comment]
I was able to reproduce this with a legacy token. This token is your user's token, so now the bot runs as _you_. That causes the [code that prevents message loops](https://github.com/slack-ruby/slack-ruby-bot/blob/790e02b9706907231a1d5e382d8620c58398f506/lib/slack-ruby-bot/hooks/message.rb#L5) to return `true`. It basically thinks that the bot is talking to itself, which is obviously a bad idea for humans.

Other users would not see this problem, or you can allow message loops as I did in https://github.com/snex/pokerstove_slack_bot/pull/1

**Comment by snex** [comment]
Is this not still a problem that the normal bot token cannot connect at all?

**Comment by dblock** [comment]
I am not sure what "normal bot token" means, but that's a question for Slack (I don't work for Slack).
