### ISSUE TITLE
Question: canonical way to find Slack user that just messaged bot

### ISSUE THREAD

**Issue by cabello** [slack-ruby/slack-ruby-bot#224]
Hi 👋 

I am not sure if I am doing this right, I want to find the current Slack user that just messaged the bot, for example this is what I've been doing:

```ruby
module Commands
  class Hi < SlackRubyBot::Commands::Base
    command 'hi' do |client, data, _match|
      user_from_slack = client.users.find { |id, _| id == data.user }[1]
      message = "You go by #{user_from_slack.name} and I can contact you via email at #{user_from_slack.profile.email}"
      client.say(channel: data.channel, text: message)
    end
  end
end
```

Is that correct? Should I expect this list of users to be updated automatically? It does point to real time models https://github.com/slack-ruby/slack-ruby-client/tree/e6a327686308f5be56866a9a25e16ffe26a8c9cb/lib/slack/real_time but I am not sure what they mean.

Thanks! 🙏

**Comment by cabello** [comment]
Alternatively I could also do:

```ruby
client.users.to_h[data.user]
```

And also using the client (not sure if this one works):

```ruby
client.users_info(user: data.user)
```

**Comment by dblock** [comment]
Yes, [the default store tracks all the changes](https://github.com/slack-ruby/slack-ruby-client#slackrealtimestoresstore). That said, it's probably not 100% reliable as the bot may be in the middle of (re)starting and potentially miss updates. If this is something you don't do frequently I recommend `users_info`, which is an API call.

I'll close this, but feel free to add more questions.

**Comment by dblock** [comment]
[Here](https://github.com/slack-ruby/slack-ruby-client/blob/e6a327686308f5be56866a9a25e16ffe26a8c9cb/lib/slack/real_time/stores/store.rb#L540) is the event handler, btw.
