### ISSUE TITLE
Automatically print a list of commands when asking for help

### ISSUE THREAD

**Issue by dblock** [slack-ruby/slack-ruby-bot#24]
Like https://github.com/mziwisky/slack-gamebot/commit/2baef46989edd552d7468dde11738bd293e028fe.

**Comment by laertispappas** [comment]
Isn't this implemented in the following revision? 

`3002bd2afc3d4a3cb9a5f44e03bf94a05b12f1ab`

**Comment by dblock** [comment]
Closing
