### ISSUE TITLE
Testing other code execution inside a command

### ISSUE THREAD

**Issue by CeeBeeUK** [slack-ruby/slack-ruby-bot#247]
So I have a simple command that shows the user a typing message while queuing a sidekiq job that processes a long running task and outputs further details...
``` ruby
module MyBot
  module Commands
    class IntegrationTests < SlackRubyBot::Commands::Base
      command 'run tests' do |client, data, _match|
        client.typing(channel: data.channel)
        StartIntegrationTestsWorker.perform_async(data)
      end
    end
  end
end
```
My simple test ensures that start_typing is received..
``` ruby
require 'spec_helper'

describe MyBot::Commands::IntegrationTests, :vcr do
  let(:user_input) { "#{SlackRubyBot.config.user} run tests" }

  context 'when user requests a test run' do
    it 'starts typing' do
      expect_any_instance_of(StartIntegrationTestsWorker).to receive(:perform_async)
      expect(message: user_input, channel: 'channel').to start_typing(channel: 'channel')
    end
  end
end
```

Is there a way to successfully test the execution of code other than the chat message?
This all works in reality, but despite trying the above and...
```expect(StartIntegrationTestsWorker).to receive(:perform_async)```
```
let(:double) { class_double(StartIntegrationTestsWorker) }
expect(double).to receive(:perform_async)
```
and other varieties I cannot successfully get the tests to simulate calling the `StartIntegrationTestsWorker`.
Do the `start_typing`, `respond_with_slack_message` and other rspec matchers mock out the entire process?  If so, is there a guide anywhere for testing other code handling inside commands?

**Comment by dblock** [comment]
I think the issue is simpler here. You are calling `StartIntegrationTestsWorker.perform_async`, which is a class method on `StartIntegrationTestsWorker`, not an instance method. The above `expect_any_instance_of` is expecting an instance, `StartIntegrationTestsWorker.new`, and so doesn't work.

The `expect(StartIntegrationTestsWorker).to receive(:perform_async)` version should work. Are you sure it does not?

**Comment by dblock** [comment]
The `start_typing`, and `respond_with_slack_message` and other rspec matchers [setup hooks](https://github.com/slack-ruby/slack-ruby-bot/blob/922954689aef62b2658273def2bcf14f62b7e7f3/lib/slack-ruby-bot/rspec/support/slack-ruby-bot/start_typing.rb) and keep track of the `client` instance, so you don't have to.

**Comment by dblock** [comment]
Minor, but I don't remember if we handle commands with spaces, `run tests`. If it doesn't work try without?

**Comment by CeeBeeUK** [comment]
I started with ```expect(StartIntegrationTestsWorker).to receive(:perform_async)```
and have also tried ```expect(StartIntegrationTestsWorker).to receive(:perform)``` in case ruby magic was translating it internally!
Both fail with 
```shell 
(StartIntegrationTestsWorker (class)).perform(*(any args))
           expected: 1 time with any arguments
           received: 0 times with any arguments
```
This is actually working nicely in Slack!
![gif-complete](https://user-images.githubusercontent.com/7482902/77923122-e40f6b80-7299-11ea-8297-fa58aee5e095.gif)
If I take out the `StartIntegrationTestsWorker` line the `start_typing(channel: 'channel')` test passes fine 🤔 
Thanks for the response and clarification, knowing that it **should** work, I'll keep playing!

Thanks for maintaining all these repos!

**Comment by CeeBeeUK** [comment]
Hmm, looking at my other tests, I am using a different format
```ruby
expect { perform }.to change(MonitorTestRunWorker.jobs, :size).by(1)
```
In the same tests 
```ruby
      it 'works?' do
        expect(MonitorTestRunWorker).to receive(:perform)
        perform
      end
```
fails.

Can I call message_send in a block?

**Comment by dblock** [comment]
> If I take out the `StartIntegrationTestsWorker` line the `start_typing(channel: 'channel')` test passes fine 🤔

Is this code valid at all? Add a `puts` above to see if it's called? Then wrap it in an exception handler, maybe there's a typo? :) 

```ruby
command 'run tests' do |client, data, _match|
  begin
        client.typing(channel: data.channel)
        StartIntegrationTestsWorker.perform_async(data)
  rescue Exception => e
      puts e
      raise
  end
end
```

See anything?

**Comment by dblock** [comment]
> Can I call message_send in a block?
> failing, but something like
> 
> ```ruby
>     it 'triggers the sidekiq job' do
>       expect { SlackRubyBot::Hooks::Message.new(message: user_input, channel: 'channel') }
>         .to change(MonitorTestRunWorker.jobs, :size).by(1)
>     end
> ```

yes you can

**Comment by dblock** [comment]
If you're still having trouble, feel free to upload the project somewhere and I can try to help.

Either way this is 100% not a problem with the bot library, I'm going to close this for housekeeping, but feel free to add more questions and I'll do my best to answer.
