### ISSUE TITLE
Deployment tutorial needs update

### ISSUE THREAD

**Issue by voscarmv** [slack-ruby/slack-ruby-bot#248]
The deployment guide in [here](https://github.com/slack-ruby/slack-ruby-bot/blob/master/DEPLOYMENT.md) has not been updated to include a mention about Slack's "New App" upgrade.

Currently, you have to create the app as a ["Classic Slack App"](https://api.slack.com/authentication/migration#classic) and then create a [legacy bot](https://api.slack.com/legacy/custom-integrations/bot-users), in order for the slack-ruby-bot gem to work. So far, I have never been able to connect to the "New Apps" I created, by using slack-ruby-bot.

Maybe update the deployment guide to show this image instead of the image it currently shows:

![image](https://user-images.githubusercontent.com/2739245/77939663-bcf27300-7274-11ea-807a-71f196aa380d.png)

**Comment by dblock** [comment]
Please PR!

**Comment by voscarmv** [comment]
@dblock PR here https://github.com/slack-ruby/slack-ruby-bot/pull/251
