### ISSUE TITLE
Migration to non-legacy bots

### ISSUE THREAD

**Issue by dblock** [slack-ruby/slack-ruby-bot#252]
The rtm integration is now legacy. See #251. What do we need to do to un-legacy a slack-ruby-bot?

**Comment by voscarmv** [comment]
I've prepared [this google document](https://docs.google.com/document/d/1RwdYVlN44_3kacYYPLzCrYvmt6BCl2hcckjfq-mRqes/edit?usp=sharing) to illustrate the trouble I came across with when trying to get a New Slack App to work with my [Stackbot project](https://github.com/voscarmv/stackbot)

The document contains the sequence of steps I took to attempt to communicate with the new Slack API using my project. My Stackbot works fine with a [Classic Slack App](https://api.slack.com/authentication/migration#classic). However, it returns an error message when trying to communicate with a New Slack App.

There is some documentation for [migrating classic apps](https://api.slack.com/authentication/migration) apparently. However, it's beyond my skill set, and I probably won't have the time right now to go through the learning curve. I hope the information I've posted here at least helps as a starting point.

Cheers!

**Comment by dblock** [comment]
Thanks, this step-by-step guide explains clearly the issue in https://github.com/slack-ruby/slack-ruby-bot/issues/241. The newer bots require that you install them via oauth, which is what https://github.com/slack-ruby/slack-ruby-bot-server is about.

**Comment by dblock** [comment]
@voscarmv You can turn your bot project into one of those bots with a "add to slack" button fairly easily, then you don't have to do any of the token work by hand.

**Comment by voscarmv** [comment]
@dblock I'll check it out, thanks!

**Comment by wasabigeek** [comment]
Based on what I can tell from [slack-ruby-server](https://github.com/slack-ruby/slack-ruby-bot-server/blob/75a2f5fa4913e431c39307e8601b5c2015f972c7/lib/slack-ruby-bot-server/server.rb#L12), the new OAuth token can be used as a drop-in replacement for the classic Bot User token, and it's valid till manually revoked (no refresh)? So the quick approach might be to migrate via [Slack's UI](https://api.slack.com/authentication/migration#overview) and do the OAuth process manually to obtain the token, and then use that as SLACK_API_TOKEN 🤣 

If we want to support the OAuth flow in this repo, then that means the user must:
- setup an API to handle the authorization grant
- have a persistence option to save the token

On our end, maybe:
- allow the App to run without tokens configured, and have users update the token in the authorization grant API? (I guess that could be problematic without other changes throughout the codebase)

Is this what you were thinking of? Or was it something more along the lines of "how do I migrate from this to slack-ruby-server"?

**Comment by dblock** [comment]
> @dblock Is this what you were thinking of? Or was it something more along the lines of "how do I migrate from this to slack-ruby-server"?

I think the latter, and/or some clarification in README to what people are supposed to do. One option is use slack-ruby-bot-server, another is roll out your own oauth (for which we don't have an example).
