### ISSUE TITLE
without mention in channel bot can't reply

### ISSUE THREAD

**Issue by fadhlimaulidri** [slack-ruby/slack-ruby-bot#268]
can the bot reply member chat in channel without mention?

<img width="698" alt="Screenshot 2020-07-16 at 15 13 51" src="https://user-images.githubusercontent.com/11204909/87644943-ff35b680-c776-11ea-8ac8-da3cbadbf97e.png">

**Comment by dblock** [comment]
Yes, there are a few ways to do this:

1. Operators, messages prefixed with an operator, https://github.com/slack-ruby/slack-ruby-bot#commands-and-operators.
2. Match and scan, https://github.com/slack-ruby/slack-ruby-bot#generic-routing
3. Using a :message hook, https://github.com/slack-ruby/slack-ruby-bot#hooks

This is a common question, if someone (you) could build a demo and document this better I'd appreciate that.
