### ISSUE TITLE
is there an example for how to implement a conversational bot using slack-ruby-bot?

### ISSUE THREAD

**Issue by rainchen** [slack-ruby/slack-ruby-bot#275]
A conversational bot can have a multi-turn dialogue with a user. The conversational bot cycle usually involves asking a question, parsing the response, and asking the next appropriate question until the task is complete. 

here is an conversational bot example: https://www.twilio.com/blog/build-a-slackbot-with-twilio-autopilot

**Comment by dblock** [comment]
I don't know of an example.

You should be using https://github.com/slack-ruby/slack-ruby-bot-server-events instead of this, btw.
