### ISSUE TITLE
Re-use the Client for the web server

### ISSUE THREAD

**Issue by klaustopher** [slack-ruby/slack-ruby-bot#63]
Hey,

I have been playing around with the framework over the weekend and I want to implement a bot that listens to chat but also has some webhooks (i.e. hook it up to GitHub to react to events that happen with our pull-requests). I set it up like you did in [the tutorial](https://github.com/dblock/slack-ruby-bot/blob/master/TUTORIAL.md) and everything worked when I stayed within the Slack world ...

But when I wanted to send something to the chat room from the web server I ran into an issue. The `client` property on the `SlackMathbot::Bot` is private and I cannot access it from the sinatra app. In #20 and #31 you basically suggest to use `Slack::Web::Client.new` directly... But since my bot already has a connection to the server open, I don't really see why it should be needed to create another connection to the Slack server.

Am I just missing a way to access the client directly?

**Comment by dblock** [comment]
In theory I think there's no harm exposing `client`, outside of the bot, you might want to test it with `.send(:client)` and if that works feel free to PR a change. You might want to reach into `client.web_client` if you need the web one that was used to open the connection in the first place.

Also, generally, I'm interested in expanding slack-ruby-bot with support for web hooks and such, maybe merging parts or all of https://github.com/dblock/slack-bot-server or turning the latter into a framework (see https://github.com/dblock/slack-bot-server/issues/3).

**Comment by klaustopher** [comment]
Ok, good, I thought I was really missing something when looking at the code. The "hack" with `send(:client)` is what I ended up doing, but it felt so ugly that I had to wash my hands after writing this code :joy:

I'll take a look at the referenced issues. I think there's something missing between "Running a bot that only replies to chat" and "Running a full slack integration available to others" ;)

**Comment by dblock** [comment]
@klaustopher I think https://github.com/dblock/slack-ruby-bot-server is the beginning of the answer for the missing link.

**Comment by klaustopher** [comment]
@dblock Thanks, this looks good. I'll definitely take a look ;)

**Comment by dblock** [comment]
This is related to https://github.com/dblock/slack-ruby-bot-server/issues/6.

I think we should either expose `client` as is, or delegate calls to it. Thoughts? PRs?

**Comment by ShiroiKuma** [comment]
Has there been any progress on exposing client? I have a bot running very nicely, but I'd like the ability to have the bot message users after a specific rails api call too. I'm not familiar with the send(:client) hack mentioned above, could someone elaborate a bit?

**Comment by kstole** [comment]
This issue seems to revolve around the same discussion as supporting [slash commands](https://github.com/slack-ruby/slack-ruby-bot/issues/66) and [webhooks](https://github.com/slack-ruby/slack-ruby-bot/issues/68).

I'm also extremely interested in this and I ran into the same issues as @klaustopher. I was previously using [Lita](https://www.lita.io/), which includes a built-in web server, but this library is much nicer for working with Slack so it would be nice if it could also include a web server.

I'm not a Ruby expert. @dblock do you think it makes more sense to look into slack-ruby-bot-server or to try the hacky `.send(:client)`? @klaustopher do you have any sample code you could share for your `.send(:client)` solution?

**Comment by dblock** [comment]
See my comment above for `client`, but generally I would like native webhook support in slack-ruby-bot-server.

**Comment by dblock** [comment]
Slash commands and webhooks require a web server. I've released https://github.com/slack-ruby/slack-ruby-bot-server-events that has full support for those.
