### ISSUE TITLE
How to match against incoming webhooks?

### ISSUE THREAD

**Issue by soshea** [slack-ruby/slack-ruby-bot#66]
I want to match against data being posted from an incoming Webhook and can not get it to match.  I can match the same the same data against users without any problems.

Can anyone please advise 

Cheers

**Comment by dblock** [comment]
slack-ruby-bot doesn't support webhooks, it doesn't carry a web server - this is something I'd like to do though, leaving this as a feature request

**Comment by dblock** [comment]
Closing because out of scope. See https://github.com/slack-ruby/slack-ruby-bot-server/issues/85 for a replacement.
