### ISSUE TITLE
How deploy Rails app + Slack Bot

### ISSUE THREAD

**Issue by igorkasyanchuk** [slack-ruby/slack-ruby-bot#88]
Hello,
I've a Ruby app + I've a slack bot in this app.
I want to deploy them.
Before I've added bot I'd everything working well and deployed using Passenger.
Now I don't know how I can start bot.
In samples - bot is added in initializers, which means even when I run "rake db:migrate" it's starting Bot.

What I can do, what are the best practices?
Thanks
Igor

**Comment by dblock** [comment]
I think a good place to start the bot is in `config.ru`. It's safe to say that starting a bot when running `rake db:migrate` is wrong, so if the sample does that, I'd appreciate a fix!

**Comment by igorkasyanchuk** [comment]
I've tried it too, but not sure how it will work if we have 3 instances of rails app in nginx

**Comment by dblock** [comment]
It won't. You need a single process for the bot itself, otherwise you literally have 3 bots connected with the same token. So you need a way to only start it once, I am not sure what the best one is, possibly separating the bot into another application.

Also see https://github.com/dblock/slack-ruby-bot/issues/14, would love some help.

**Comment by igorkasyanchuk** [comment]
@dblock yes, a way with 2 processes in 1 config.ru was not working.
So I've created a new config.ru in folder "bot" and starting bot there. But I've noticed it's working a bit unstable. For example it might not be available, when I'm trying to access my main app first time. It's strange because "Idle Pool Timeout" was set to 0. But a bit later it was working again.

does anyone has bot running in production as a separate process?

**Comment by dblock** [comment]
I am not sure how this whole Sinatra interaction is working. I'm running bots using [slack-ruby-bot-server](https://github.com/dblock/slack-ruby-bot-server), eg. https://github.com/dblock/slack-market.

**Comment by igorkasyanchuk** [comment]
@dblock looks good, but just a few questions:

1) how do you deploy it?
2) how stable it works?
3) Also, do you use Active Record models from Rails app? Or does it has an integration with Rails app?

**Comment by dblock** [comment]
1) I use Dokku on DigitalOcean, so `git push dokku master` :) Same for Heroku.
2) It's 100% stable, my services run 24/7 no issues.
3) I don't use Rails, but that's beyond the point, it works fine with AR and what not. If you check slack-ruby-bot-server it's Rack + Grape + Mongoid.

**Comment by igorkasyanchuk** [comment]
@dblock thanks
a quick question, to run slack-ruby-bot-server - server need's to be accessible from internet? what if I use private network for VPS, then I can use only slack-ruby-bot? My assumption is correct?

**Comment by dblock** [comment]
I don't think your assumption is correct. 

Slack-ruby-bot-server is just an opinionated boilerplate service that can run multiple slack-ruby-bot instances. It's to save you time building a service with many bots with Slack button integration. If you're building one custom bot you're fine where you are.

**Comment by dblock** [comment]
Closing in favor of an older #14.
