### ISSUE TITLE
Closed sockets and connection restarts

### ISSUE THREAD

**Issue by zenmatt** [slack-ruby/slack-ruby-bot#91]
We've been using slack-ruby-bot for months without problems. I've noticed in the last few weeks, we are getting lots of closed sockets and connection restarts. Has anyone else noticed this issue? 
I was wondering if something might have changed with Slack's realtime API that could be causing the problem. It starts happening immediately after we start our individual team connections and appears to be random.

**Comment by dblock** [comment]
I am seeing the same thing with my production bots. Reconnecting just works though automatically. I would open a ticket with Slack to find out, I suspect that they are seeing high load on a server and disconnect the clients to force them to reconnect to a server that has less load.

**Comment by zenmatt** [comment]
I checked with Slack and they're not seeing a problem. They are load balancing the connections which might be causing some of the reconnections. 

We're around 300 teams and our last few restarts have been awful - the disconnect/reconnect cycle seems to be amplified with our server crashing multiple times. Things eventually settle down and stabilize, then I see very few reconnections and everything runs fine (until our next deployment). I haven't seen anything change in the API which might be causing this, any ideas on where to look?

**Comment by dblock** [comment]
I also opened a ticket with Slack on this and got the same response. I'll point them to here as well.

**Comment by fsadeq** [comment]
We've noticed the same thing with the real-time-client. However, there is no automatic reconnecting and the socket remains closed. I haven't seen anything in the API regarding this, any suggestions?

**Comment by dblock** [comment]
That's the same behavior as here, @fsadeq. The code in slack-ruby-bot does the same as what you do - it attempts to reconnect (aka call `rtm.start` yada yada).

**Comment by dblock** [comment]
According to Slack this has been fixed. Also make sure to update slack-ruby-client, this helped isolate and fix a leak, https://github.com/slack-ruby/slack-ruby-client/issues/104

![screen shot 2016-08-30 at 11 27 10 am](https://cloud.githubusercontent.com/assets/542335/18095458/0edd5144-6ea5-11e6-9f5a-0784859e8cf0.png)
