### ISSUE TITLE
How to set bot as typing

### ISSUE THREAD

**Issue by richlewis14** [slack-ruby/slack-ruby-bot#99]
Hi

is it all possible for a "is typing" gif or text whilst the bot is getting it's response? i have an api call taking place and it takes 3 seconds to come back and would like to show the user something is happening

Thanks

**Comment by dblock** [comment]
Yes, see https://github.com/slack-ruby/slack-ruby-client#realtime-client.

```ruby
client.typing channel: data.channel
```
